#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0

until false; do
    echo "Best School"
    ((i++))
    if [[ $i -lt 10 ]]; then 
        continue
    else
        break
    fi
done

