#!/usr/bin/env bash
#Displays Best School 10 times while untering the 9th iteration using the while loop
i=1

while [ "$i" -lt 11 ] 
do
    echo "Best School"
        if [[ $i -eq 9 ]] 
            then
                echo "Hi"
        fi
    ((i++))
done
