#!/usr/bin/env bash
# comments here

case "$1" in
 	start)
# starts manage_my_process in the background		
 	./var/run/manage_my_process &
# creates /var/run/my_process.pid with its PID inside
 	echo $$>/var/run/my_process.pid
# then display manage_my_process started
	echo "manage_my_process started"
	;;
	
	stop)
	# kill manage_my_process	
	pkill -f ./manage_my_process
# delete /var/run/my_process.pid with force option and sudo to make sure it’s deleted
	sudo rm /var/run/my_process.pid
# then display it has been stopped
	echo "manage_my_process stopped"
	;;
	
	restart)
# stops manage_my_process
 	pkill -f ./manage_my_process
# deletes /var/run/my_process.pid
	sudo rm /var/run/my_process.pid
 # starts manage_my_process : start and stop should be refactored to functions
 	./manage_my_process &
# creates /var/run/my_process.pid with its PID inside
         echo $$>/var/run/my_process.pid
 	echo "manage_my_process restarted"
         ;; 

 	*)
 	echo "Usage: manage_my_process {start|stop|restart}"
 esac
